Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: false

AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  Enabled: false

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
